static-components:
  - dir: jbossorg
    kind: git
    spec:
      url: https://github.com/jbossorg/jbossorg.github.io.git
      ref: master
      dir: /
  - dir: example
    kind: git
    spec:
      url: https://github.com/navendu-pottekkat/navendu-pottekkat.github.io.git
      ref: master
      dir: /
  - dir: netflix
    kind: git
    spec:
      url: https://github.com/Netflix/netflix.github.com.git
      ref: master
      dir: /
